### ISSUE TITLE
Edge Flags Download with Virus

### ISSUE THREAD

**Issue by fluxlabs** [Bill-Stewart/SyncthingWindowsSetup#11]
https://www.virustotal.com/gui/file/f37cbbdd971b8ec6d26becb4a0fbfdd5c553d08f84ee6a849dd9bd6439972bdb

Flagged on Virus Total

**Comment by fluxlabs** [comment]
![Screenshot 2023-08-04 at 10 41 52 AM](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/211150/f56b0cf9-75d7-4031-9390-1a7bb747b393)


Flagged by Windows Defender as well.

**Comment by Bill-Stewart** [comment]
Closing this issue as these detections are false-positives.
