### ISSUE TITLE
syncthing service, running under SyncthingServiceAcct, Failed to save config \\?\C:\ProgramData\Syncthing\config.xml: Access is denied.

### ISSUE THREAD

**Issue by crackwitz** [Bill-Stewart/SyncthingWindowsSetup#14]
I did not migrate anything. This is a fresh install that was completely inoperative and threw repeated error messages at me in the administrative page (localhost:8384).

Since the service runs under `SyncthingServiceAcct`, it has no access to the aforementioned config directory or config file.

I manually granted that user full permissions on that directory.

I did take a look at the readme, *after* encountering this issue and figuring that I should grant full permissions to that service user on the config directory.

I think the setup is missing a step or two. And some explanations, right in the setup.

If you think that reading the readme is mandatory, then make the installer open it.

I don't see a reason why the setup shouldn't at least take care of the permissions on the config directory. Setup should set this so a default install doesn't require user intervention to even work on a basic level.

I'd also appreciate if the setup caused a browser to open the local admin page (localhost:8384) after setup is done.

**Comment by Bill-Stewart** [comment]
Also: Thanks for the suggestion to open the config page when Setup completes. The next version will have a checkbox on the last wizard page to do just that.

**Comment by Bill-Stewart** [comment]
Issue has been fixed in v1.26.0.
