### ISSUE TITLE
Error launching configuration page post-installation

### ISSUE THREAD

**Issue by kzha0** [Bill-Stewart/SyncthingWindowsSetup#17]
**Describe the bug:**

An error dialog that appears after installation

**To Reproduce:**

1. Launch the installer `syncthing-1.27.2-setup.exe`
2. Follow the steps
3. Select Administrative (system-wide) install mode.
4. Tick the option to launch configuration page after completing installation.
5. Click finish

**Expected behavior:**

The installer should open the browser and redirect the user to the configuration page (which is on `https://127.0.0.1:8384` by default)

**Actual behavior:**

The installer failed to open the browser and instead showed an error dialog.

**Screenshots:**

![image](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/81629650/b81ba10b-5e37-47c0-83ac-ac9e377eccd6)

**Additional context:**

I am using Windows 10 LTSC.

**Comment by kzha0** [comment]
I looked into the problem and realized that the issue is not related to the installer, my apologies.

It seems that the issue is related to my system configuration and the way windows handles default programs for specific files, including `.url` files.

**Comment by kzha0** [comment]
I looked into the problem and realized that the issue is not related to the installer, my apologies.

It seems that the issue is related to my system configuration and the way windows handles default programs for specific files, including .url files.

**Comment by Bill-Stewart** [comment]
Thanks for the update. You are correct that the file association needs to be in place for the post-install configuration launch page to open correctly.
