### ISSUE TITLE
Cannot get past the Eula screen in V1.27 Setup Installer 

### ISSUE THREAD

**Issue by simonallisonuk** [Bill-Stewart/SyncthingWindowsSetup#19]
Setup shows the Eula but cannot click Next or Cancel, X works to cancel setup, works fine on v1.26 setup

**Comment by Bill-Stewart** [comment]
Sorry, but I'm not able to reproduce this. Do you have anti-malware or other software that might be blocking the installer from continuing?

**Comment by simonallisonuk** [comment]
Windows 11 with defender only , v1.26 worked flawlessly  then it updated to the latest

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bill-Stewart** [comment]
Sorry, but I'm not sure what could be wrong as the problem you are reporting is part of core Inno Setup functionality. I can't reproduce it on any of my Windows 11 systems. As I don't have access to your system, it's difficult for me to provide any suggestions other than to try on a different machine and see if you have the same problem.

**Comment by TheGarageDragon** [comment]
I believe the software is getting flagged by Windows Smartscreen.

**Comment by Bill-Stewart** [comment]
> I believe the software is getting flagged by Windows Smartscreen.

If that was the case, the installer wouldn't launch at all, I think. The problem description says the readme license shows but then the "Next" button seemingly doesn't do anything.

**Comment by Bill-Stewart** [comment]
@simonallisonuk - Can you try again with v1.27.3 (just released) and see if you have the same problem?
