### ISSUE TITLE
Windows Script Host: Cannot find script file

### ISSUE THREAD

**Issue by luruijie23** [Bill-Stewart/SyncthingWindowsSetup#22]
C:Users\...\Syncthing\StartSyncthing.js

I tried a bunch of things like sfc/ scannow or editing the regedit with https://www.winhelponline.com/blog/error-there-is-no-script-engine-for-file-extension-when-running-js-files/ but both didn't work

FYI I uninstalled the application and deleted the config folder so idk why it is still trying to run this file
![Screenshot (64)](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/71773795/2d4820bf-df19-4381-842e-8c9c67139c58)

**Comment by Bill-Stewart** [comment]
When does that message appear? When you log on? If so, go to the Task Scheduler and delete the task that runs `StartSyncthing.js` at logon. (Starting with 1.27.3, Syncthing Windows Setup does not use `StartSyncthing.js` anymore.)

**Comment by luruijie23** [comment]
tysm, this fixed the issue
