### ISSUE TITLE
NO ISSUE - just wish to say excellent job

### ISSUE THREAD

**Issue by cpadesign** [Bill-Stewart/SyncthingWindowsSetup#23]
Hi Bill,

Merely wish to say you've done an excellent job with this, especially after the demise of syncthingrazor. I've successfully installed on 2 instances (Windows 11 x2) with no issue. The only exception was a request for a windows firewall additional rule on one install, while the other didn't make the same request (both were clean Win11 installs, latest version as of Feb 2024).

The only thing lacking for semi-computer literate users would be some method of notifying the user in the event of a failure. Of course, the system is so simple (relatively speaking), there's little to go wrong!

All the best,

Chris

**Comment by Bill-Stewart** [comment]
Thanks for the feedback.

> The only exception was a request for a windows firewall additional rule on one install, while the other didn't make the same request

The only time Syncthing Windows Setup prompts to add the firewall rule is if it needs to. When you installed and didn't get the prompt, Syncthing Windows Setup must have detected that the firewall rule already existed or you were running in administrative install (per computer) mode. (In admin install mode, Setup doesn't need to prompt because it is already running with administrative permissions and thus doesn't need to prompt; it just adds the firewall rule without prompting.)

> some method of notifying the user in the event of a failure

Can you be more specific?

**Comment by Bill-Stewart** [comment]
I appreciate the feedback! If you see something isn't working correctly with the installer, or if you'd like to see an enhancement, this is the right place to ask.

**Comment by cpadesign** [comment]
Apologies for the delay response. 

> The only time Syncthing Windows Setup prompts to add the firewall rule is if it needs to. When you installed and didn't get the prompt, Syncthing Windows Setup must have detected that the firewall rule already existed or you were running in administrative install (per computer) mode. (In admin install mode, Setup doesn't need to prompt because it is already running with administrative permissions and thus doesn't need to prompt; it just adds the firewall rule without prompting.)

Thank you for explaining, very kind of you.

> Can you be more specific?

The installer is great, works flawlessly, absolutely no complaints here!

I know it's beyond the scope of your installer, but the original syncthingrazor was quite helpful as it had a taskbar icon.

I did reflect on my own comment with this. I have no intention of comparing ST with the main stream syncing applications as that would simply be unfair. Something that is helpful for an average user though, is the ability to hover over an icon and have a reassuring message like this

![Screenshot 2024-03-22 071202](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/145531589/4146596b-193d-4313-91de-24f0d0524009)

Verification that it's working at a glance, is helpful. With ST, the only way at present is to either open the browser and go to 127..., or manually check that each device has the correctly dated and timed file.

 I personally 100% trust ST, it has proven itself to me during the last 18 months, it's great that my data isn't going out the building, only to return to another machine on the same network.

I hope this helps, but by all means disregard if it's off topic - and thank you again for a superb installer!
