### ISSUE TITLE
Unable to install v1.27.6 on Windows Server 2019 Standard

### ISSUE THREAD

**Issue by sinya0909** [Bill-Stewart/SyncthingWindowsSetup#28]
Could not install v1.27.6 on Windows Server 2019 Standard.
The installer - appears to be down.
I was able to install v1.27.5 with no problems.

**Comment by Bill-Stewart** [comment]
"Appears to be down" is not a good description of the problem. What does this mean? I can't reproduce it.

**Comment by sinya0909** [comment]
When I ran syncthing-1.27.6-setup.exe on Windows Server 2019 Standard, 
"appears to be down" was how I described the situation where the exe would not run.
I repeated the download and run several times, but it did not run and I did not see anything that looked like it in the process.
Windows Server 2019 Standard is on-premises, 
processor is Intel(R) Xeon(R) E-2226G CPU@3.40GHZ, 
15.85GB of installed memory.
If there is anything we should try, we will try it and report back.

**Comment by sinya0909** [comment]
Also, Windows Server 2019 Standard here is used in a Japanese environment.

**Comment by Bill-Stewart** [comment]
I have installed on Server 2022 and had no issues. I would make sure you don't have antivirus or antimalware software running that might be interfering. Other than that, I don't know what might be wrong as I am not able to reproduce it.

**Comment by sinya0909** [comment]
I have disabled the firewall and the installed antivirus software, E-SET, but the exe does not seem to start. I am currently able to install 1.27.5 without any problems, so I will close this issue for now.
Thank you for your response.
Also, thank you for making something so useful.
