### ISSUE TITLE
Very slow Windows <-> Android  & Windows <-> Docker in Lan 

### ISSUE THREAD

**Issue by Frikigi** [Bill-Stewart/SyncthingWindowsSetup#29]
Hello,

I've installed this Syncthing app to windows. First I try to sync a Windows Folder with my Android Phone (Galaxy Z Flip 5) in lan. The sync is very very slow (3 Ko/s). Second i try to sync a folder with my Android Phone to Rsync Docker in Lan, the sync was quick. Folder sync Android phone to Windows is not working (no speed).
I disable relay and i try to enter manualy the IP adress device's to my W11 computer but it was also slow. 
I think the problem is with my Syncthing W11 install.
The log don't show anormal logs.

![image](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/4548449/b67e3ef6-4972-4c10-bb23-7b495f678fcf)

Can you help me to resolve this ? 
TY

**Comment by Bill-Stewart** [comment]
> Can you help me to resolve this ?

Unfortunately no. This list is for reporting issues with the installer. This is mentioned in the documentation:

https://github.com/Bill-Stewart/SyncthingWindowsSetup#reporting-problems
