### ISSUE TITLE
Running Syncthing on startup

### ISSUE THREAD

**Issue by jarble** [Bill-Stewart/SyncthingWindowsSetup#30]
According to the documentation [here](https://docs.syncthing.net/users/autostart.html), Syncthing does not have an official installer for Windows and will not start automatically unless users manually create a shortcut in the Startup folder.

Should the installer create this shortcut during installation so that users will not need to create it manually?

**Comment by Bill-Stewart** [comment]
That documentation is referring to when you download the `syncthing.exe` executable manually from the official sources and want to set up automatic startup manually. In contrast, Syncthing Windows Setup (this installer) does this for you. In other words, if you use this installer, you don't need the instructions in the Syncthing documentation.

I would recommend reading the documentation for Syncthing Windows Setup here:

https://github.com/Bill-Stewart/SyncthingWindowsSetup

Hope this helps.
