### ISSUE TITLE
doesn't auto-start sometimes when laptop isn't plugged in

### ISSUE THREAD

**Issue by dinesh-58** [Bill-Stewart/SyncthingWindowsSetup#31]
I've noticed this happening sometimes when my files aren't syncing after I first boot my laptop. Changing battery mode to High Performance doesn't do anything but if I plug in the charger, it starts. If I manually start Syncthing, then upon plugging in, another instance is started but it closes with a dialog box since another is already open. Haven't checked if Syncthing always starts only when plugged in.

**Comment by Bill-Stewart** [comment]
I am guessing, but it sounds like perhaps you installed 1.27.5 or older in per-user mode? 1.27.5 and older created the scheduled task to only start when not on batteries (see [Syncthing Windows Setup Version History](https://github.com/Bill-Stewart/SyncthingWindowsSetup/blob/main/history.md). The first thing to try would be to upgrade to 1.27.6 or newer, and make sure the `startatlogon\acpoweronly` task is not enabled (this corresponds to the **Start automatically only if the computer is running AC power** checkbox on the **Additional Tasks** wizard page).

**Comment by dinesh-58** [comment]
Apologies. I was meaning to try this out someday and close the issue. This worked so thanks for the help.
