### ISSUE TITLE
Sync Speed

### ISSUE THREAD

**Issue by LC44Y** [Bill-Stewart/SyncthingWindowsSetup#32]
Is it normal for the client sending data to send at 15 Mbps (the maximum upload rate at that location) for a few seconds, then stop for a few seconds? Meanwhile, the receiving client always receives data at 3-4 Mbps without interruptions. Is there a way to speed this up?

**Comment by Bill-Stewart** [comment]
This list is for reporting issues with Syncthing Windows Setup, not for Syncthing itself. Please see the following:

https://github.com/Bill-Stewart/SyncthingWindowsSetup#reporting-problems
