### ISSUE TITLE
Library Access when installed as Admin

### ISSUE THREAD

**Issue by heliophane** [Bill-Stewart/SyncthingWindowsSetup#35]
Howdy! 

First off, this installer is great! It makes using syncthing significantly easier! So thank you!

I used the admin installation option, but I have a folder in my documents folder that I would like to add to my sync chain. However, the Service account doesn't have access to my libraries for my User account. How do I let it access these folders? I apologize if this isn't the proper place to ask.

**Comment by Bill-Stewart** [comment]
Please see the documentation:

[Granting Folder Permissions for the Service Account](https://github.com/Bill-Stewart/SyncthingWindowsSetup?tab=readme-ov-file#granting-folder-permissions-for-the-service-account)
