### ISSUE TITLE
Malware in installer detected

### ISSUE THREAD

**Issue by trashken** [Bill-Stewart/SyncthingWindowsSetup#37]
![image](https://github.com/user-attachments/assets/50eca7b6-2a50-47dc-b2c5-e358b7d5f0ee)

Getting a malware warning from Windows Defender

**Comment by Bill-Stewart** [comment]
Please review the issues list here. The overwhelming majority of them are about false-positive malware detections. This is another one, of course. I have submitted this false-positive detection to the Windows Defender team.
