### ISSUE TITLE
Autostart does nothing, never autostarts

### ISSUE THREAD

**Issue by ToothyDev** [Bill-Stewart/SyncthingWindowsSetup#39]
When installing syncthing on Windows, it gives you a toggle on whether you want it to start on user logon. Yet, it does nothing. It doesn't start on logon, nor does it register a service, put a shortcut in the startup folder or even just a task scheduler entry. Nothing. Why have this toggle if it does nothing? This happens regardless of running syncthing's installer with admin or not.

**Comment by ToothyDev** [comment]
I'm talking about this checkbox
![image](https://github.com/user-attachments/assets/5c4b41ad-a51b-4521-afe3-4a3825aa65b5)
It's selected by default (i also tried unchecking and rechecking it), though, well, nothing happens apparently (as i said, no service or task scheduler or anything i can find) and syncthing does indeed not start on login even after giving it a few minutes. I'm using the per user mode.
I'm on Windows 11 as well, latest update and all. For funs i also tried checking the toggle below that only autostarts when connected to AC (i dont have a laptop but might as well) but equally, no autostart

**Comment by ToothyDev** [comment]
Also, I just remembered that i get the following error when installing, everytime and even with admin
![image](https://github.com/user-attachments/assets/3d9fc7c0-120e-4cb4-99ab-5f148476ceff)
Might be related

**Comment by Bill-Stewart** [comment]
Yes. You need to fix that error first.

**Comment by Bill-Stewart** [comment]
See this issue also:

https://github.com/Bill-Stewart/SyncthingWindowsSetup/issues/20

This is not a Syncthing Windows Setup issue but rather something broken on your machine. I can't reproduce it.

**Comment by ToothyDev** [comment]
Alright, I did some digging and found a fix. Thought it might help others to keep this here

I went to `HKEY_CLASSES_ROOT\.js` in the registry and changed `(Default)` back to `JSFile`. PHPstorm (which i don't even have installed anymore) was still registered there, and after rerunning the install, syncthing also properly set up a task in the task scheduler.

**Comment by Bill-Stewart** [comment]
Thanks for the update and the fix!

**Comment by yatmund** [comment]
> Alright, I did some digging and found a fix. Thought it might help others to keep this here
> 
> I went to `HKEY_CLASSES_ROOT\.js` in the registry and changed `(Default)` back to `JSFile`. PHPstorm (which i don't even have installed anymore) was still registered there, and after rerunning the install, syncthing also properly set up a task in the task scheduler.

Thanks for this! No idea how my one got borked, but this did the trick!

**Comment by Bill-Stewart** [comment]
The next version of Setup will check if this value is correct and abort the install if it's missing or incorrect.
