### ISSUE TITLE
[Update Request] Version 1.27.12 installer

### ISSUE THREAD

**Issue by Dragon1573** [Bill-Stewart/SyncthingWindowsSetup#40]
## Summary

Install `v1.27.11` will get `v1.27.12` shown in the configuration page. Is it expected? Where is `v1.27.12` installer released?

## Steps to reproduce

1. Download and install the [latest stable release](https://github.com/Bill-Stewart/SyncthingWindowsSetup/releases/latest) from tag [`v1.27.11`](https://github.com/Bill-Stewart/SyncthingWindowsSetup/releases/tag/v1.27.11).
2. _Syncing_ will automatically start after the installation.
3. Enter the configuration page (`https://127.0.0.1:8384/`), I see version `v1.27.12`.
4. Version `v1.27.12` is currently not available from _GitHub Releases_.

## Additional information

- https://github.com/microsoft/winget-pkgs/pull/172324#issuecomment-2336738017
- https://github.com/microsoft/winget-pkgs/pull/172324#issuecomment-2338574411

**Comment by Bill-Stewart** [comment]
The v1.27.11 information at the top of the Syncthing installer represents the version of the installer itself, not the version of Syncthing it will install. I can see how that can be confusing. With an online installation it will still download and install the latest version of Syncthing. Hope this helps.
