### ISSUE TITLE
no valid release since 1.27.10 ?

### ISSUE THREAD

**Issue by cestpasmoicestlautre** [Bill-Stewart/SyncthingWindowsSetup#44]
the .exe files after v1.27.10 are not valid,
also the size is greatly inferior (26MB -> 4MB)

i cannot install these versions, do you see a build/packaging problem?

thank you

**Comment by Bill-Stewart** [comment]
The much smaller size is correct because the installer no longer includes the Syncthing binaries; instead it downloads the proper file from GitHub. Please see the documentation and history file.

"I cannot install": Why not? (Remember, I can't see your screen.)

**Comment by ericderace** [comment]
![image](https://github.com/user-attachments/assets/de8ae41d-7cd8-4c2d-8407-e97947ba749d)
Here's the error I get when trying to install the latest from the github releases page on Windows 11 22H2

**Comment by ericderace** [comment]
v1.27.11 works for me

**Comment by Bill-Stewart** [comment]
@ericderace This is a separate issue. I created a new issue for you and posted the link to how to fix.

**Comment by cestpasmoicestlautre** [comment]
ok I get it,
since we are in a closed environment (no direct internet access) the machine cannot download the binaries

**Comment by Bill-Stewart** [comment]
> ok I get it, since we are in a closed environment (no direct internet access) the machine cannot download the binaries
> 
> do you think it would be feasable to let me specify a url to download the binaries (so I would host & update them locally)?

Please read the documentation section "Offline Installation":

https://github.com/Bill-Stewart/SyncthingWindowsSetup#offline-installation
