### ISSUE TITLE
Setup initialization error: WSH script registration is not valid

### ISSUE THREAD

**Issue by Bill-Stewart** [Bill-Stewart/SyncthingWindowsSetup#45]
https://github.com/user-attachments/assets/de8ae41d-7cd8-4c2d-8407-e97947ba749d

Here's the error I get when trying to install the latest from the github releases page on Windows 11 22H2

_Originally posted by @ericderace in https://github.com/Bill-Stewart/SyncthingWindowsSetup/issues/44#issuecomment-2422485605_

**Comment by Bill-Stewart** [comment]
@ericderace did the instructions in the documentation link I posted resolve the problem?

**Comment by ericderace** [comment]
@Bill-Stewart I didn't try the fix - I simply used an older version of the installer and that worked for me.

**Comment by szmq2** [comment]
> @ericderace did the instructions in the documentation link I posted resolve the problem?
Yes, I solved the same problem using this method, thanks!

**Comment by Monking-21** [comment]
> This is documented already. You need to fix `.js` in your registry.
> 
> https://github.com/Bill-Stewart/SyncthingWindowsSetup/#invalid-wsh-script-registration

it is worked ,Thank you
