### ISSUE TITLE
Observability, notifications when things go wrong

### ISSUE THREAD

**Issue by timkgh** [Bill-Stewart/SyncthingWindowsSetup#46]
Given there is no tray app/icon, what is the recommended way to notice and get notified when things are not working, e.g. failed syncs, conflicts, etc?

**Comment by Bill-Stewart** [comment]
Keep in mind that Syncthing is a cross-platform application and doesn't have a native Windows notification mechanism. Accordingly, you need to open the Syncthing GUI page to view status. (This question really has nothing to do with Synchthing Windows Setup.)

**Comment by timkgh** [comment]
I understand all that. I am just surprised people don't care to know that their sync might have issues. It sounds to me like a simple tray icon with a simple status would be very useful to alert users on sync issues.

**Comment by Bill-Stewart** [comment]
This project is _only_ an installer for Syncthing on Windows. It does not add any features to the core Syncthing tool and has no ambitions to do so. I understand you'd like a Windows notification mechanism, but that's beyond the scope of this project.

Another way of saying this: You're asking for this in the wrong place.

**Comment by nv2p** [comment]
For anyone landing here, I think the simple (GUI) way is to use the separate (cross-plateform) tray icon program: https://github.com/Martchus/syncthingtray. @Bill-Stewart I think a tiny chapter in the readme, just stating something like "A tray icon isn't in the scope of this project, but check the [Syncthing Community contributions](https://docs.syncthing.net/users/contrib.html#contrib-all) for a standalone solution to this." could be nice.
