### ISSUE TITLE
Consider setting the service to restart if the syncthing process dies

### ISSUE THREAD

**Issue by timkgh** [Bill-Stewart/SyncthingWindowsSetup#47]
If the syncthing _process_ dies, the service should attempt to restart it, hence keeping the sync alive.

This is common practice on Linux systemd for example, but not sure exactly how services work on Windows, what we should enter on the Recovery tab in the service props and whether any customization users make get reset when SyncthingWindowsSetup gets and update and it's run again.

**Comment by Bill-Stewart** [comment]
Is this just a general recommendation, or are you actually seeing process failures and needing to restart the service manually?

**Comment by timkgh** [comment]
> Is this just a general recommendation, or are you actually seeing process failures and needing to restart the service manually?

Too early to tell whether it ever crashes as I just started using it on Windows, but I did kill it once by accident and it got me thinking about reliability. Given there is no monitoring/tray icon, you can go for a while without realizing that syncthing possibly crashed.

**Comment by timkgh** [comment]
What happens when running the setup again? Will it reset any Recovery changes I may have made to the service?
It's unclear to me if I ever need to run the setup again once it's installed. Not sure whether we are supposed to pick up new releases whether they change anything in a meaningful way.

**Comment by Bill-Stewart** [comment]
1) A reinstall isn't going to uninstall the service, so any custom changes you made to the service will remain in place.

2) The Syncthing executable automatically upgrades itself (that is, unless you've disabled the automatic upgrade feature). See the Syncthing docs for more information on that.

**Comment by timkgh** [comment]
> 2. The Syncthing executable automatically upgrades itself (that is, unless you've disabled the automatic upgrade feature). See the Syncthing docs for more information on that.

Yes, I understand the syncthing auto-upgrade. I was wondering whether I'd ever need to run SyncthingWindowsSetup again, is there a scenario besides switching between all users and current user modes that would require re-running SyncthingWindowsSetup?

(Sorry to have a discussion in a closed issue. Suggestion: enable Discussions for the GitHub project.)

**Comment by Bill-Stewart** [comment]
> I was wondering whether I'd ever need to run SyncthingWindowsSetup again, is there a scenario besides switching between all users and current user modes that would require re-running SyncthingWindowsSetup?

Not that I can think of.

**Comment by Bill-Stewart** [comment]
> I was wondering whether I'd ever need to run SyncthingWindowsSetup again, is there a scenario besides switching between all users and current user modes that would require re-running SyncthingWindowsSetup?

Actually I need to update my previous answer to this: If any of the [helper tools](https://github.com/Bill-Stewart/SyncthingWindowsSetup/?tab=readme-ov-file#helper-tools) get updated, installing an updated version of Syncthing Windows Setup would install the latest versions of those, so there's an advantage there.

**Comment by timkgh** [comment]
> > I was wondering whether I'd ever need to run SyncthingWindowsSetup again, is there a scenario besides switching between all users and current user modes that would require re-running SyncthingWindowsSetup?
> 
> Actually I need to update my previous answer to this: If any of the [helper tools](https://github.com/Bill-Stewart/SyncthingWindowsSetup/?tab=readme-ov-file#helper-tools) get updated, installing an updated version of Syncthing Windows Setup would install the latest versions of those, so there's an advantage there.

Should `shawl` also be on that list?

**Comment by Bill-Stewart** [comment]
> Should `shawl` also be on that list?

It is (or rather will be when I next update, probably at the beginning of next month).
