### ISSUE TITLE
Error in version number and file

### ISSUE THREAD

**Issue by myrandor** [Bill-Stewart/SyncthingWindowsSetup#49]
Syncthing has not version 1.27.28. It should be 1.28.0.

**Comment by Bill-Stewart** [comment]
Correct. 1.27.28 is the version of Syncthing Windows Setup, not Syncthing itself.

Syncthing Windows Setup now downloads the latest version of Syncthing from GitHub, so the version number of Syncthing Windows Setup does not match the version of Syncthing any longer.
