### ISSUE TITLE
Simplify the installer, e.g. by hiding more advanced options

### ISSUE THREAD

**Issue by tomasz1986** [Bill-Stewart/SyncthingWindowsSetup#51]
Since the installer was officially recommended at https://syncthing.net/downloads, replacing SyncTrayzor (which had its own issues) in the process, we have been flooded with issues on the forum related to permissions. This seems to be mainly caused by the users installing Syncthing as an administrative service even though they just use a single user account on their system, so theoretically there should be no business in using the administrative mode (or, as a matter of fact, the service itself too).

In other words, in my opinion, they should just be installing Syncthing as a user application. However, as the installer presents all those options, many users opt for them without sufficient understanding about the consequences. Because of all that, I would like to kindly suggest to simplify the installer, perhaps leaving the user installation as the default, and hiding all the service/administrative options under an "advanced" or "expert" switch.

Just to give an example, even the very first screen, i.e.

![image](https://github.com/user-attachments/assets/13aa13de-80de-47e0-9f0a-0da826040cfe)

is confusing to the average user, because they have no idea what the difference between the two is, or what having "administrative privileges" actually does.

**Comment by calmh** [comment]
> In other words, in my opinion, they should just be installing Syncthing as a user application.

That is the deployment scenario we've always envisioned/recommended/expected for almost all users. Anything other than that is a complication.

**Comment by Bill-Stewart** [comment]
Understood, and thank you for the feedback!

What do you all think of the following proposed installer changes:

1. Do not display the dialog at all, and default to installing for the current user.

2. If a user wants to install the service, they will need to specify `/allusers` on the installer's command line.

**Comment by calmh** [comment]
That sounds reasonable to me

**Comment by tomasz1986** [comment]
May be annoying for those that do need the advanced installation methods, however I also agree that limiting the GUI to the basic user installation is probably the most reasonable solution 🙂.

**Comment by Bill-Stewart** [comment]
> > In other words, in my opinion, they should just be installing Syncthing as a user application.
> 
> That is the deployment scenario we've always envisioned/recommended/expected for almost all users. Anything other than that is a complication.

...

> May be annoying for those that do need the advanced installation methods, however I also agree that limiting the GUI to the basic user installation is probably the most reasonable solution 🙂.

This position seems entirely sensible to me. If an end-user is not advanced enough to know how to add a command-line option to the installer when they run it, they're probably not advanced enough to understand that permissions need to be set if they install as a service (and how to do so). For this reason, it seems reasonable to make non administrative (per user) installation mode the default. For those that really want the service, they can still get it, but they have to specify `/allusers`.
