### ISSUE TITLE
With Windows Service installation and NTFS encrypted folders, created files can't be opened

### ISSUE THREAD

**Issue by fbreve** [Bill-Stewart/SyncthingWindowsSetup#52]
When Syncthing is installed as a service and the synced folders are NTFS encrypted, files that came from other devices cannot be opened due to encryption issues. 

I don't know if I did something wrong, but the permissions were granted to the system account. The files are created, but always inaccessible. 

This issue does not happen in another machine where the folders are not encrypted.

**Comment by fbreve** [comment]
But these files are not encrypted in the computer they came from. These files are probably being encrypted as they are created in the computer with encrypted folders. I guess the encryption is tied to the service account and the files cannot be opened by the local account even though the local account has all the permissions to access them.

Anyway, I uninstalled the service and installed again to my account only and the problems are gone (for files synced from now on).

**Comment by Bill-Stewart** [comment]
Right--I'm not an expert with NTFS encryption, but my understanding is that that account writing the file would need to have the private key in order to decrypt files. In any case, this is really an issue that doesn't have anything to do with Syncthing Windows Setup per se.
