### ISSUE TITLE
On reinstall/update please preserve user service customizations to startup type

### ISSUE THREAD

**Issue by timkgh** [Bill-Stewart/SyncthingWindowsSetup#54]
I changed the service startup type from "Automatic (Delayed Start)" to "Automatic" because I use SyncthingTray and it complains when I log in to Windows if the Syncthing service is not yet running. I have not noticed any issues with starting the service right away vs delayed.

But when I run "syncthing-windows-setup /allusers" again to pick up any updates, it resets the service back to delayed start.

FWIW, it is nice that it preserves any customizations made in the Recovery settings 👍 

Thank you.

**Comment by Bill-Stewart** [comment]
Reinstalling will reinstate automatic delayed start. This is by design. I don't currently have any plans to change this, but if there are lots of requests for it, I might be persuaded to change it. You might also consider switching to per-user rather than running the service.

**Comment by Bill-Stewart** [comment]
I don't have any plans to remove the service or change the `/allusers` parameter requirement.
