### ISSUE TITLE
Exectable download is being flagged as having the [HEUR/APC] virus

### ISSUE THREAD

**Issue by nadsrsnug** [Bill-Stewart/SyncthingWindowsSetup#55]
The exectable download is being flagged as having the [HEUR/APC] virus with the TotalAV AntiVirus program.  After downloading syncthing-windows-setup.exe, TotalAV Threat Prevented the executable with [HEUR/APC].and quarantines the file. 

![Screenshot 2024-12-21 162100](https://github.com/user-attachments/assets/da6be378-8aad-4074-b291-8c76e83dbc79)

**Comment by nadsrsnug** [comment]
Is there a way around this?On Dec 21, 2024, at 5:14 PM, Bill Stewart ***@***.***> wrote:﻿
Closed #55 as not planned.

**Comment by Bill-Stewart** [comment]
Yes. Exclude the file from scanning and report the false positive to your antivirus software vendor. You also have the option of using a different antivirus software that does a better job and doesn't misidentify legitimate software incorrectly as malware.

**Comment by nadsrsnug** [comment]
I just wanted to say I uploaded the .exe to VirusTotal’s online scanner site and not a single vender detected a problem :-).  I have since sent a request to TotalAV to exclude it. Thanks again. On Dec 21, 2024, at 7:25 PM, Bill Stewart ***@***.***> wrote:﻿
Yes. Exclude the file from scanning and report the false positive to your antivirus software vendor. You also have the option of using a different antivirus software that does a better job and doesn't misidentify legitimate software incorrectly as malware.
