### ISSUE TITLE
This gets tagged as a virus by Windows Security

### ISSUE THREAD

**Issue by mrtolkien** [Bill-Stewart/SyncthingWindowsSetup#6]
By default, this executable gets flagged as a virus, making it hard to use on Windows without shutting down Windows Security:
![image](https://user-images.githubusercontent.com/8489650/192921619-7f59f932-bd00-49c1-a1fb-47f5166bd8c1.png)

Any clue what might be causing that?

**Comment by Bill-Stewart** [comment]
This is known as a "false positive" because the security tool is flagging something as malware that is not malware. Please submit the package to the vendor as a false positive.
