### ISSUE TITLE
An error occured while trying to rename a file in the destination directory

### ISSUE THREAD

**Issue by pavlikpatrycja** [Bill-Stewart/SyncthingWindowsSetup#8]
Hi, 
I'm trying to use latest syncthing-1.21.0-setup.exe with parameters for silent installation /silent /allusers /log="dir" /norestart on Windows Server 2019 in default directory C:\Program Files\Syncthing. Unfortunatelly I get this error: 
![image](https://user-images.githubusercontent.com/14920046/200317986-3298966c-18c5-4d27-bcff-0a08f6127a35.png)
Installation on Windows 10 and Windows Server 2016 was successful.

**Comment by pavlikpatrycja** [comment]
Ok I noticed that it is related to https://github.com/Bill-Stewart/SyncthingWindowsSetup/issues/7 as my antivirus is blocking this file...

**Comment by Bill-Stewart** [comment]
Right, usually the problem is an antimalware software. Please report the file to your antimalware software vendor as a false-positive.
