### ISSUE TITLE
Password Issues

### ISSUE THREAD

**Issue by jstraten** [Bill-Stewart/SyncthingWindowsSetup#9]
Is this fork using the same config file than the original? I am having trouble resetting the password by removing the user and password entry from the config file. Any suggestions? I have also posted on the Syncthing forum itself.

https://forum.syncthing.net/t/login-password-popup-after-updating-config-file/19791/3

Thank you for any feedback!

**Comment by Bill-Stewart** [comment]
See the documentation section on [finding the Syncthing configuration folder](https://github.com/Bill-Stewart/SyncthingWindowsSetup#finding-the-syncthing-configuration-folder).

**Comment by jstraten** [comment]
My installation is using the config.xml file located in C:\ProgramData\Syncthing.

Unfortunately, the file does not have a user id or password in it. I have posted the whole file on the Syncthing forum, but waiting on moderator approval before it shows up.

**Comment by Bill-Stewart** [comment]
If updating the correct config file [according to the recommendation](https://forum.syncthing.net/t/901) doesn't work, unfortunately there's nothing I can suggest because this is just an installer.
